name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main # This will trigger the action when you push to the 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Install dependencies and build the project
      - run: npm ci && npm run build

      # Step 3: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BAG_SOCIETY_2D720 }}
          channelId: live
          projectId: bag-society-2d720
